def transliterate(string):
    trans = {'А': 'A',
             'Б': 'B',
             'В': 'V',
             'Г': 'G',
             'Д': 'D',
             'Е': 'E',
             'Ё': 'E',
             'Ж': 'Zh',
             'З': 'Z',
             'И': 'I',
             'Й': 'I',
             'К': 'K',
             'Л': 'L',
             'М': 'M',
             'Н': 'N',
             'О': 'O',
             'П': 'P',
             'Р': 'R',
             'С': 'S',
             'Т': 'T',
             'У': 'U',
             'Ф': 'F',
             'Х': 'Kh',
             'Ц': 'Tc',
             'Ч': 'Ch',
             'Ш': 'Sh',
             'Щ': 'Shch',
             'Ы': 'Y',
             'Э': 'E',
             'Ю': 'Iu',
             'Я': 'Ia',
             'а': 'a',
             'б': 'b',
             'в': 'v',
             'г': 'g',
             'д': 'd',
             'е': 'e',
             'ё': 'e',
             'ж': 'zh',
             'з': 'z',
             'и': 'i',
             'й': 'i',
             'к': 'k',
             'л': 'l',
             'м': 'm',
             'н': 'n',
             'о': 'o',
             'п': 'p',
             'р': 'r',
             'с': 's',
             'т': 't',
             'у': 'u',
             'ф': 'f',
             'х': 'kh',
             'ц': 'tc',
             'ч': 'ch',
             'ш': 'sh',
             'щ': 'shch',
             'ъ': '',
             'ы': 'y',
             'ь': '',
             'э': 'e',
             'ю': 'iu',
             'я': 'ia',
             'Ъ': '',
             'Ь': ''}
    ans = ''
    for letter in string:
        ans += trans.get(letter, letter)
    return ans


def create_login(name, surname):
    n3 = transliterate(name[:4])
    s3 = transliterate(surname[:4])
    return f'{n3}{s3}'
